### ISSUE TITLE
Add an option to cancel unflipping

### ISSUE THREAD

**Issue by veteran29** [veteran29/vet_unflipping#9]
Needs to be done if unflipping time option would allow bigger values.

**Comment by McDiod** [comment]
Seconded. We would like to use this addon, but need this feature first. Do you need any help with this? I can PR if that speeds it up.

**Comment by veteran29** [comment]
I'm busy right now and have no time to implement this, so if you have time feel free to PR that.

Current implementation is kinda "lazy", if server sees it has enough people it just schedules the unflip after certain time and forces people to stay still for that time. (it could use an animation too)
https://github.com/veteran29/vet_unflipping/blob/master/addons/unflipping/XEH_preInitServer.sqf#L18-L23

Contributions always welcome!

**Comment by McDiod** [comment]
Working on it, concept so far is:

* replace server side unflip scheduling wait time with a continuous check for `vet_unflippingUnits < _requiredUnits`
* send vet_unflipping_unflip_stop event to server, if client aborts unflipping progressBar
* if remaining unflippingUnits are < _requiredUnits, enter fnc_unflipAction waiting progressBar again

Currently having trouble differentiating between different progressBar failure modes. User who hit ESC is supposed to send unflip_stop event to server. Users who did not hit ESC, but are aborted, because _requiredUnits threshold is no longer met, should not send unflip_stop event.

The needed error code argument will hopefully be added in the next CBA release.
https://github.com/CBATeam/CBA_A3/pull/1177

**Comment by veteran29** [comment]
Concept logic seems solid for me. 👌
